services:
  # ===================== ZOOKEEPER =====================
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    restart: always
    environment:
      ZOO_ALLOW_ANONYMOUS_LOGIN: "true"
    ports:
      - "2181:2181"
    networks:
      - svjob_network

  # ===================== KAFKA =====================
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_started
    networks:
      - svjob_network

  # ===================== EUREKA DISCOVERY SERVICE =====================
  discovery-service:
    build: ./discovery_service
    container_name: discovery-service
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    # XÃ“A: depends_on: - mariadb
    networks:
      - svjob_network

  # ===================== API GATEWAY =====================
  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_started
    networks:
      - svjob_network

  # ===================== AUTH SERVICE =====================
  auth-service:
    build: ./auth_service
    container_name: auth-service
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== USER SERVICE =====================
  user-service:
    build: ./user_service
    container_name: user-service
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== EMPLOYER SERVICE =====================
  employer-service:
    build: ./employer_service
    container_name: employer-service
    restart: always
    ports:
      - "8086:8086"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== NOTIFICATION SERVICE =====================
  notification-service:
    build: ./notification_service
    container_name: notification-service
    restart: always
    ports:
      - "8090:8090"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - kafka
      - discovery-service
    networks:
      - svjob_network

  # ===================== ADMIN SERVICE =====================
  admin-service:
    build: ./admin_service
    container_name: admin-service
    restart: always
    ports:
      - "8085:8085"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== JOB SERVICE =====================
  job-service:
    build: ./job_service
    container_name: job-service
    restart: always
    ports:
      - "8084:8084"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - kafka
      - discovery-service
    networks:
      - svjob_network

  # ===================== PAYMENT SERVICE =====================
  payment-service:
    build: ./payment_service
    container_name: payment-service
    restart: always
    ports:
      - "8094:8094"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== APPLICATION SERVICE =====================
  application-service:
    build: ./application_service
    container_name: application-service
    restart: always
    ports:
      - "8087:8087"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - kafka
      - discovery-service
    networks:
      - svjob_network

  # ===================== STORAGE SERVICE =====================
  storage-service:
    build: ./storage_service
    container_name: storage-service
    restart: always
    ports:
      - "8083:8083"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      minio:
        condition: service_started
      discovery-service:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads
    networks:
      - svjob_network

  # ===================== CHATBOT SERVICE =====================
  chatbot-service:
    build: ./chatbot_service
    container_name: chatbot-service
    restart: always
    ports:
      - "8089:8089"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== CV-AI SERVICE =====================
  cv-ai-service:
    build: ./cv_ai_service
    container_name: cv-ai-service
    restart: always
    ports:
      - "8093:8093"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== RECOMMENDATION SERVICE =====================
  recommendation-service:
    build: ./recommendation_service
    container_name: recommendation-service
    restart: always
    ports:
      - "8091:8091"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      elasticsearch:
        condition: service_started
      discovery-service:
        condition: service_started
    networks:
      - svjob_network

  # ===================== MESSAGE SERVICE =====================
  message-service:
    build: ./message_service
    container_name: message-service
    ports:
      - "8092:8092"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== COMMENT SERVICE =====================
  comment-service:
    build: ./comment_service
    container_name: comment-service
    ports:
      - "8088:8088"
    env_file:
      - ./global.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - discovery-service
    networks:
      - svjob_network

  # ===================== MINIO =====================
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_storage:/data
    command: server /data --console-address ":9001"
    networks:
      - svjob_network

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      minio:
        condition: service_started
    networks:
      - svjob_network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        echo "Waiting for MinIO...";
        until mc alias set local http://minio:9000 minioadmin minioadmin; do
          echo "MinIO not ready, retrying...";
          sleep 2;
        done;
        echo "Creating bucket 'storage-files'...";
        mc mb local/storage-files || true;
        echo "Setting bucket 'storage-files' public download...";
        mc anonymous set download local/storage-files || true;
        echo "Init done.";


  # ===================== ELASTICSEARCH =====================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=FL3xuyOWffeGRqVy96Ko
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - svjob_network
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9200 || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 30s
# ===================== VOLUMES & NETWORKS =====================
volumes:
  elasticsearch_data:
  minio_storage:

networks:
  svjob_network:
    driver: bridge